Devise gem
curtydudes/rails-trio-stock-app pull request #4
Opened 2021-09-14 12:20 UTC by curtydudes

this push is to set up the devise gem for both user and admin. I also added a temporary landing page for the path to the sign up page

2021-09-15 05:14 UTC, analyn-cajocson requested changes

2021-09-15 05:14 UTC, analyn-cajocson commented on app/views/landing/signupUser.html.erb
> +# link_to 'Home page', root_path
delete unnecessary comments

2021-09-15 05:14 UTC, analyn-cajocson commented on app/views/landing/signupUser.html.erb
> +# link_to 'Home page', root_path
and please rename this file base on rails convention

2021-09-15 05:14 UTC, analyn-cajocson commented on config/routes.rb
> +  root 'landing#signupUser'
please follow rails convention

2021-09-15 05:14 UTC, analyn-cajocson commented on spec/rails_helper.rb
> -end
Better not to delete these codes

2021-09-15 05:14 UTC, analyn-cajocson commented on spec/model/trial_user_spec.rb
> +    expect(user1).not_to be_valid
This is so confusing, you're test is `is valid with valid attributes` but you're expecting an invalid result

2021-09-15 05:14 UTC, analyn-cajocson commented on spec/model/trial_user_spec.rb
> +    expect(user1).not_to be_valid
Try to complete the attributes since this test is a happy path test

2021-09-15 05:14 UTC, analyn-cajocson commented on spec/model/trial_user_spec.rb
> +  end
Be specific with your test. If you are testing the validation presence of attribute `last_name` then you should provide the values to the rest of the user's attributes except for `last_name`. Or you may better use this gem https://github.com/thoughtbot/shoulda

2021-09-15 05:14 UTC, analyn-cajocson commented on spec/models/trial_user_spec.rb
> +end
Duplicate specs: `spec/model/trial_user_spec.rb`

2021-09-15 05:39 UTC, curtydudes commented
This code address the Trader -- User Story 1&2. I also added here the RSPEC Model for users. 

I set up multiple devise accounts following the wiki here for devise: https://github.com/heartcombo/devise/wiki/How-to-Setup-Multiple-Devise-User-Models. Following this, I will create a function where the Admin can only login their credentials as the sign up will happen in the console as per the wiki. 

Models: 
I got to create an admin and user models.

Views: 
Devise automatically created admin and user views while I manually added a landing folder with a temporary landing page called signupUser.html.rb (will be changing this name appropriately)

Controllers: 
Created a landing page temporarily to set up shop and to have some pseudo base
An admins controller and users controller was generated by Devise 

SCREENSHOTS: 
To start, I made a temporary landing page to set up the routes nicely. 
![image](https://user-images.githubusercontent.com/81552806/133374401-8398bef8-0855-4611-b23d-1b033a5ed09e.png)

I still don't have the buttons to route them but I will place them soon or in the next PR. 

Admins Log-In 
![image](https://user-images.githubusercontent.com/81552806/133376630-55e001f1-9baf-4a90-b277-5f1be66c5218.png)

Admins Sign-up --- to be deleted and have it signed up at console
![image](https://user-images.githubusercontent.com/81552806/133376734-d2b27b09-4c52-4ba0-b33a-e2d27ba641a0.png)

User Sign-up
![image](https://user-images.githubusercontent.com/81552806/133376696-7b9a29f9-5017-499e-b05d-31279f8a0130.png)

User Log-in
![image](https://user-images.githubusercontent.com/81552806/133376865-762b4a41-e01a-4e10-8b6a-37beab9e0023.png)

Forgot Your Password 
![image](https://user-images.githubusercontent.com/81552806/133376894-52dc2edf-bec9-4725-aabd-53c59df7ef02.png)

2021-09-16 12:07 UTC, analyn-cajocson requested changes

2021-09-16 12:07 UTC, analyn-cajocson commented on config/routes.rb
> +  root 'landing#signupUser'
@curtydudes please change this

2021-09-16 12:16 UTC, analyn-cajocson approved these changes

2021-09-16 12:20 UTC, merged